# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug directory structure
      run: ls -R # Lists all files and directories to verify the location of pom.xml
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file Fesadyab/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DrepositoryId=github::default::https://maven.pkg.github.com/SHKSH2002/ST-Base2 -f Fesadyab/pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
